"""Add is_default to Template

Revision ID: 5155baa3c4d9
Revises: 0007
Create Date: 2026-05-23 02:04:23.982820

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '5155baa3c4d9'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('is_default', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'is_default')
    # ### end Alembic commands ###
